#pragma once

// didkit.h - autogenerated by cbindgen

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Verify a Verifiable Credential. Arguments are a C string containing the Verifiable Credential
 * to verify, and a C string containing a JSON object for the linked data proof options for
 * verification. The return value is a newly-allocated C string containing a JSON object for the
 * verification result, or `NULL` in case of certain errors. On successful verification, the
 * verification result JSON object contains a "errors" property whose value is an empty array. If
 * verification fails, either `NULL` is returned and the error can be retrieved using
 * [`didkit_error_message`], or a verification result JSON object is returned with an "errors" array
 * containing information about the verification error(s) encountered. A string returned from this
 * function should be freed using [`didkit_free_string`].
 */
const char *verify_credential(const char *credential, const char *proof_options_json);